version: '3'

services: 
  www:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
